sudo: false
language: node_js
node_js:
- "8"

before_script:
  - npm install

script:
  - node_modules/nyc/bin/nyc.js npm test && node_modules/nyc/bin/nyc.js report --reporter=text-lcov | ./node_modules/.bin/coveralls
