sudo: false
language: node_js
node_js:
- "8"

cache:
  yarn: true
  directories:
  - node_modules/

before_script:
  - npm install

script:
  - npm test

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
